homeassistant: false
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://172.17.0.1
  user: '!secret.yaml user'
  password: '!secret.yaml password'
frontend: true
devices: devices.yaml
