
# for config & display
units = "celsius"

[service_http_addresses]
dx2wlogger = "192.168.50.193:4006"
controller = "192.168.50.193:4005"
thermostat = "192.168.50.193:4004"
mqttserver = "192.168.50.193:4003"
actuators  = "192.168.50.193:4002"
dashboard  = "192.168.50.193:4001"
ntfyserver = "192.168.50.193:8081"

[dx2w_modbus]
tcp_address = "192.168.50.60:502"
device_id = 200

[location] # for weather data
latitude = "45.360114"
longitude = "-75.803988"

[mqtt]
address = "192.168.50.193:1883"
prefix = "burlo"
user = "hvac"
pass = "hvac_pass"

[thermostat.mqtt]
prefix = "/zigbee2mqtt/thermostats"
user = "hvac"
pass = "hvac_pass"

[controller.radiant_cooling]
enabled = true
overnight_boost = true
supply_temperature = 18 # celsius

[controller.phidgets] # actuators
circulator = {hubport = 0, channel = 0, type="digital_output"}
hpmode = {hubport = 0, channel = 1, type="digital_output"}
dewpoint = {hubport = 1, channel = 0, type="voltage_output"}
