#!/usr/bin/sh
echo "configuring for Sonoff dongle plus P"
export ZIGBEE2MQTT_CONFIG_SERIAL_PORT=/dev/ttyACM0
export ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER=ezsp
export ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID=0xDEAD

echo ZIGBEE2MQTT_CONFIG_SERIAL_PORT ${ZIGBEE2MQTT_CONFIG_SERIAL_PORT}
echo ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER ${ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER}
echo ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID ${ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID}

docker-compose -f ./docker-compose-sonoffP.yaml up -d
