#!/usr/bin/sh
echo "configuring for Sonoff dongle plus E"
export ZIGBEE2MQTT_CONFIG_SERIAL_PORT=/dev/ttyUSB0
export ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID=0xBEEF
export DEVICE_PORT_MAPPING=/dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0:${ZIGBEE2MQTT_CONFIG_SERIAL_PORT}

echo DEVICE_PORT_MAPPING ${DEVICE_PORT_MAPPING}
echo ZIGBEE2MQTT_CONFIG_SERIAL_PORT ${ZIGBEE2MQTT_CONFIG_SERIAL_PORT}
echo ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER ${ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER}
echo ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID ${ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID}

docker compose up -d

