#!/usr/bin/sh
echo "configuring for Sonoff dongle plus P"
export ZIGBEE2MQTT_CONFIG_SERIAL_PORT=/dev/ttyACM0
export ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER=ezsp
export ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID=0xDEAD
export DEVICE_PORT_MAPPING=/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230505182833-if00:${ZIGBEE2MQTT_CONFIG_SERIAL_PORT}

echo DEVICE_PORT_MAPPING ${DEVICE_PORT_MAPPING}
echo ZIGBEE2MQTT_CONFIG_SERIAL_PORT ${ZIGBEE2MQTT_CONFIG_SERIAL_PORT}
echo ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER ${ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER}
echo ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID ${ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID}

docker-compose up -d

