#!/usr/bin/sh
echo "configuring for Sonoff dongle plus E"
export ZIGBEE2MQTT_CONFIG_SERIAL_PORT=/dev/ttyUSB0
export ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID=0xBEEF
export DEVICE_ID=usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0

echo DEVICE_ID ${DEVICE_ID}
echo ZIGBEE2MQTT_CONFIG_SERIAL_PORT ${ZIGBEE2MQTT_CONFIG_SERIAL_PORT}
echo ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID ${ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID}

docker compose up -d
